### PR TITLE
Correctly decodes stream when next parse offset is zero

### LINKED ISSUE #13: `DecodeStream` cannot decode streams with `next_parse_offset` set to zero
Bitstreams which omit the (optional) `next_parse_offset` field in the parse
info header are not correctly decoded by `DecodeStream`, typically resulting in
bizarre failures to interpret a non-existant sequence header.

For example with the following [sample bitstream](https://github.com/bbc/vc2-reference/files/4824011/absent_next_parse_offset.zip):

    $ DecodeStream absent_next_parse_offset.vc2 out.16p2
    Error: DataUnitIO: Custom Quantisation Matrix flag not supported

### PR DESCRIPTION
**Pull request by GalenReich**
Fixes #13 

Previously the code which handled the next_parse_offset (in DataUnit.cpp) assumed that next_parse_offset would only be zero at the end of a sequence and that no more bytes needed to be read.

This adds handling of the different types of data unit, throwing errors where appropriate.

The main addition is for processing pictures or fragments when next_parse_offset is zero (10.6.2). The next parse info header is found within the stream (and validated) and its prev_parse_offset is used to determine the correct number of bytes to read for the previous data unit. The stream is then rewound and processing continues using the future prev_parse_offset in place of the current next_parse_offset.

### CODE REVIEW

**Comment by GalenReich** [comment]
@mossblaser What do you think to that - it removes the reliance on the data unit class and just processes the input stream in the primary decoding loop. I think it makes it clearer what is happening and brings the proessing more in line with the spec.

File: src/Library/src/DataUnit.cpp [hunk 1]
```diff
@@ -905,95 +905,7 @@ std::istream& dataunitio::synchronise(std::istream &stream) {
...
-    d.strm.str(std::string(buf, bufsize));
-    delete[] buf;
-  }
-
-  Bytes prefix(4);
-  stream >> prefix;
-
-  d.strm.copyfmt(stream);
-
+  throw std::logic_error("Stream assignment to DataUnit is no longer supported.");
```
Comment (mossblaser) [inline src/Library/src/DataUnit.cpp:908]: If this method is now defunct, it would be better to remove it entirely (which would produce a compile-time error if anyone tried to use it) rather than throw a runtime error (which we'd only discover 'in the field' given the lack of automated tests :)).

File: src/DecodeStream/DecodeStream.cpp [hunk 2]
```diff
@@ -206,23 +207,21 @@ try { //Giant try block around all code to get error messages
       // TODO: Add proper handling
       break;
     }
-
-    DataUnit du;
-    inStream >> du;
+    
+    DataUnit d;
```
Comment (mossblaser) [inline src/DecodeStream/DecodeStream.cpp:211]: The source originally used `du` for this variable; to reduce the quantity of unrelated changes you may prefer to use that instead?

File: src/DecodeStream/DecodeStream.cpp [hunk 3]
```diff
@@ -176,7 +177,7 @@ try { //Giant try block around all code to get error messages
   int frame = 0;
   int pic = 0;
   inStream >> dataunitio::synchronise;
-
+  inStream.seekg(-4,ios_base::cur);
```
Comment (mossblaser) [inline src/DecodeStream/DecodeStream.cpp:180]: This is a bit mysterious, what is it for? (Probably needs a comment)

File: src/DecodeStream/DecodeStream.cpp [hunk 4]
```diff
@@ -253,13 +252,21 @@ try { //Giant try block around all code to get error messages
         clog << "End of Sequence after " << frame << " frames, exiting" << endl;
       }
       return EXIT_SUCCESS;
+    case AUXILIARY_DATA:
+      if (d.length()<0) throw std::logic_error("Auxilliary data length is nonconformant.");
```
Comment (mossblaser) [inline src/DecodeStream/DecodeStream.cpp:256]: Might be clearer to say 'Auxiliary data has length less than zero'?

Also, `s/Auxilliary/Auxiliary/`

File: src/DecodeStream/DecodeStream.cpp [hunk 5]
```diff
@@ -253,13 +252,21 @@ try { //Giant try block around all code to get error messages
...
+      inStream.seekg(d.length(),ios_base::cur);
+      break;
+    case PADDING_DATA:
+      if (d.length()<0) throw std::logic_error("Padding data length is nonconformant.");
```
Comment (mossblaser) [inline src/DecodeStream/DecodeStream.cpp:260]: See comment above.

File: src/DecodeStream/DecodeStream.cpp [hunk 6]
```diff
@@ -421,10 +428,9 @@ try { //Giant try block around all code to get error messages
 
         PictureHeader pichdr;
         PicturePreamble preamble;
-        du.stream() >> dataunitio::highQualityVBR(0, 1)
+        inStream >> dataunitio::highQualityVBR(0, 1)
                     >> pichdr
                     >> preamble;
```
Comment (mossblaser) [inline src/DecodeStream/DecodeStream.cpp:433]: Nit pick: indentation of these two lines no longer matches the first.

File: src/DecodeStream/DecodeStream.cpp [hunk 7]
```diff
@@ -585,14 +591,14 @@ try { //Giant try block around all code to get error messages
 
         PictureHeader pichdr;
         Fragment frag;
-        du.stream() >> dataunitio::lowDelay
+        inStream >> dataunitio::lowDelay
                     >> pichdr
                     >> frag;
```
Comment (mossblaser) [inline src/DecodeStream/DecodeStream.cpp:596]: Nit pick: Indentation again :)

File: src/DecodeStream/DecodeStream.cpp [hunk 8]
```diff
@@ -820,7 +826,7 @@ try { //Giant try block around all code to get error messages
                                                                                           qMatrix,
                                                                                           pictureHeight, width, chromaFormat);
 
-            //du.stream() >> sliceio::highQualityVBR(slicePrefix, sliceScalar)
+            //inStream >> sliceio::highQualityVBR(slicePrefix, sliceScalar)
```
Comment (mossblaser) [inline src/DecodeStream/DecodeStream.cpp:829]: I realise this was already commented out, but do you know why it might have been there? (In either case, now might be a good time to drop this dead code unless it is somehow explanatory in a way I'd not realised?)

File: src/DecodeStream/DecodeStream.cpp [hunk 9]
```diff
@@ -830,10 +836,10 @@ try { //Giant try block around all code to get error messages
               clog << "Picture " << pichdr.picture_number << ": Reading " << frag.n_slices()
                    << " slices, starting from (" << frag.slice_offset_x() << ", " << frag.slice_offset_y() << ")" << endl;
             }
-            du.stream() >> sliceio::highQualityVBR(fragmentReassemblingSlices[pichdr.picture_number]->slice_prefix,
+            inStream >> sliceio::highQualityVBR(fragmentReassemblingSlices[pichdr.picture_number]->slice_prefix,
                                                    fragmentReassemblingSlices[pichdr.picture_number]->slice_size_scalar);
```
Comment (mossblaser) [inline src/DecodeStream/DecodeStream.cpp:840]: Indentation nit!

File: src/Library/src/DataUnit.cpp [hunk 10]
```diff
@@ -919,29 +933,10 @@ std::istream& operator >> (std::istream& stream, DataUnit &d) {
   case 0xEC: d.type = HQ_FRAGMENT;     break;
   default:
     d.type = UNKNOWN_DATA_UNIT;
+    throw std::logic_error("Stream Error: Nonconformant data unit type.");
```
Comment (mossblaser) [inline src/Library/src/DataUnit.cpp:936]: `s/Nonconformant/Unknown/` ?

File: src/DecodeStream/DecodeStream.cpp (hunk 8 above)
Comment (GalenReich) [reply src/DecodeStream/DecodeStream.cpp:829]: I don't, cleaning it up sounds like a good idea :)
