### PR TITLE
Pass correct arguments to stream format function call

### LINKED ISSUE #9: `EncodeHQ-ConstQ` appears to be broken
The constant quantizer HQ profile encoder (`EncodeHQ-ConstQ`) produces
non-conforming bitstreams. Specifically, it appears to produce malformed slice
data such that each slice is larger than it should be. The resultant streams,
in some cases, fail to decode under `DecodeStream`, but in either case are
non-conforming.

As test cases, the following minimal inputs are provided:

* [Mid-Grey frame (1 frame, 10 bit, 1280x720,
4:2:2, progressive, YCbCr)](https://github.com/bbc/vc2-reference/files/4823896/mid_grey.zip)

  This mid-grey frame should can be coded with all transform coefficients set
  to zero; and therefore all slices being of minimum size. When coded by
  `EncodeHQ-ConstQ`, it appears more zero-bytes are written than expected to
  the stream.

* [Real pictures (3 frames, 10 bit, 1280x720,
4:2:2, progressive, YCbCr)](https://github.com/bbc/vc2-reference/files/4823913/real_pictures.zip) 

  A series of real pictures.

The following is used to encode:

    $ EncodeHQ-ConstQ \
        -x 1280 -y 720 -f 4:2:2 -z 10 -r 6 \
        -k LeGall -d 3 -a 2 -u 1 -q 0 -S 2 \
        input.16p2 output.vc2 

The envoded 'mid-grey' frame is correctly decoded by `DecodeStream` but is non
conforming, with the `picture_parse` data unit being 28822 bytes long, not
`36022` as the `next_parse_offset` field suggested.

The real picture case is similar, though this time the end-of-stream is
encountered before the whole picture has been decoded. This stream also fails to
decode using `DecodeStream`:

    $ DecodeStream -v output.vc2 output.16p2
    Failed to read compressed framenumber 0

### PR DESCRIPTION
**Pull request by GalenReich**
Closes #9 

Straightforward fix for a problem that took a while to track down.

When the scalar and prefix arguments were the same, no error was observed.

In the example command in #9 slicePrefix and sliceScalar should have been 0 and 1 respectively. This bug introduced an erroneous empty byte at the start of the wavelet transform data.

I've also opened #27 to address the annoying diffs arising from the mixed line endings in the repository.

### CODE REVIEW

File: src/EncodeHQ-ConstQ/EncodeHQ-ConstQ.cpp [hunk 1]
```diff
@@ -336,7 +336,7 @@ try { //Giant try block around all code to get error messages
 
         //Write packaged output
         if (verbose) clog << "Writing compressed output to file" << endl;
-        outStream << dataunitio::highQualityVBR(sliceScalar, sliceScalar); // Write output in HQ VBR mode
+        outStream << dataunitio::highQualityVBR(slicePrefix, sliceScalar); // Write output in HQ VBR mode
```
Comment (jamesba) [inline src/EncodeHQ-ConstQ/EncodeHQ-ConstQ.cpp:339]: Is this the only non-white-space change in this PR?
